version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:17"
      timezone: Australia/Melbourne
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:23"
      timezone: Australia/Melbourne
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
